name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install ale-hscript
        run: haxelib dev ale-hscript .

      - name: Build
        run: |
          cd tests
          haxe build.hxml -D VERBOSE_TEST